/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * Aluna: Talita Tortola Almeida.
 */
public class GuiAtualizaPrecoProduto extends javax.swing.JFrame {

    /**
     * Creates new form GuiAtualizaPrecoProduto
     */
    public GuiAtualizaPrecoProduto(ArrayList<Produto> cadProd) {
        initComponents();
        produto = cadProd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        txtPorcentagem = new javax.swing.JTextField();
        lblQtdeProdAtualizados = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atualizar Preço Produto");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Categoria");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Porcentagem (%)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Qtde. Produtos Atualizados");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblQtdeProdAtualizados.setText(" ");
        lblQtdeProdAtualizados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentos", "Bebidas", "Eletrônicos", "Vestuários", "Todos" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(22, 22, 22)
                                        .addComponent(cbxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 53, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblQtdeProdAtualizados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtualizar)))
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblQtdeProdAtualizados))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnAtualizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        
        if(Double.parseDouble(txtPorcentagem.getText()) < 1){
            JOptionPane.showMessageDialog(null, "Valor mínimo permitido é de 1", "Aviso", JOptionPane.ERROR_MESSAGE);
        }else{
            if(Double.parseDouble(txtPorcentagem.getText()) > 100){
                JOptionPane.showMessageDialog(null, "Valor máximo permitido é de 100", "Aviso", JOptionPane.ERROR_MESSAGE);
            }else{
                
                for(int x = 0; x < produto.size(); x++){
                    if(((produto.get(x).getCategoria().equals(cbxCategoria.getSelectedItem().toString())))
                                                && (cbxCategoria.getSelectedItem().toString().equals("Alimentos"))){

                        produto.get(x).setPreco(produto.get(x).getPreco() + (produto.get(x).getPreco() * (Double.parseDouble(txtPorcentagem.getText()) / 100)));

                        countAlimentos++;
                        lblQtdeProdAtualizados.setText(String.valueOf(countAlimentos));

                    }else{
                        if(((produto.get(x).getCategoria().equals(cbxCategoria.getSelectedItem().toString())))
                                                && (cbxCategoria.getSelectedItem().toString().equals("Bebidas"))){

                            produto.get(x).setPreco(produto.get(x).getPreco() + (produto.get(x).getPreco() * (Double.parseDouble(txtPorcentagem.getText()) / 100)));

                            countBebidas++;
                            lblQtdeProdAtualizados.setText(String.valueOf(countBebidas));

                        }else{
                            if(((produto.get(x).getCategoria().equals(cbxCategoria.getSelectedItem().toString())))
                                                && (cbxCategoria.getSelectedItem().toString().equals("Eletrônicos"))){

                                produto.get(x).setPreco(produto.get(x).getPreco() + (produto.get(x).getPreco() * (Double.parseDouble(txtPorcentagem.getText()) / 100)));

                                countEletro++;
                                lblQtdeProdAtualizados.setText(String.valueOf(countEletro));

                            }else{
                                if(((produto.get(x).getCategoria().equals(cbxCategoria.getSelectedItem().toString())))
                                                && (cbxCategoria.getSelectedItem().toString().equals("Vestuários"))){

                                    produto.get(x).setPreco(produto.get(x).getPreco() + (produto.get(x).getPreco() * (Double.parseDouble(txtPorcentagem.getText()) / 100)));

                                    countVestuario++;
                                    lblQtdeProdAtualizados.setText(String.valueOf(countVestuario));

                                }else{
                                    if(cbxCategoria.getSelectedItem().toString().equals("Todos")){

                                        produto.get(x).setPreco(produto.get(x).getPreco() + (produto.get(x).getPreco() * (Double.parseDouble(txtPorcentagem.getText()) / 100)));

                                        countTodos++;
                                        lblQtdeProdAtualizados.setText(String.valueOf(countTodos));
                                    }
                                }
                            }
                        }
                    }
                    
                }
                
            }
        }
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblQtdeProdAtualizados;
    private javax.swing.JTextField txtPorcentagem;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Produto> produto;
    private int countAlimentos = 0;
    private int countBebidas = 0;
    private int countEletro = 0;
    private int countVestuario = 0;
    private int countTodos = 0;
}
