/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * Aluna: Angélica Shigematsu.
 * Aluno: Lucas Henrique Cardoso da Aparecida.
 * Aluna: Nicole Baraldi dos Santos.
 * Aluna: Talita Tortola Almeida.
 * 
 */
public class GuiPedido extends javax.swing.JFrame {

    /**
     * Creates new form GuiPedido
     */
    public GuiPedido(ArrayList<Pedido> cadPedido, ArrayList<Pessoa> cadCliVend, ArrayList<Produto> cadProd) {
        initComponents();
        pedido = cadPedido;
        cliVend = cadCliVend;
        produto = cadProd;
        modTblPedido = (DefaultTableModel) tblItemPedido.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumPedido = new javax.swing.JTextField();
        btnConsultarPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDtPedido = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxFormaPagto = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCPFCliente = new javax.swing.JFormattedTextField();
        lblNomeCliente = new javax.swing.JLabel();
        btnConsultarCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCPFVendedor = new javax.swing.JFormattedTextField();
        lblNomeVendedor = new javax.swing.JLabel();
        btnConsultarVendedor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        btnConsultarProduto = new javax.swing.JButton();
        lblDescricao = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtQtdeVendida = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemPedido = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lblValTotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblQtdeItensPedidos = new javax.swing.JLabel();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emitir Pedido");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        jLabel1.setText("Número do Pedido");

        btnConsultarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data do Pedido");

        try {
            txtDtPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtPedido.setEnabled(false);

        jLabel3.setText("Forma de Pagamento");

        cbxFormaPagto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Vista", "Parcelado" }));
        cbxFormaPagto.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDtPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtDtPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(cbxFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cliente"));

        jLabel4.setText("CPF Cliente");

        try {
            txtCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFCliente.setEnabled(false);

        lblNomeCliente.setText(" ");
        lblNomeCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarCliente.setEnabled(false);
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnConsultarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeCliente))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Vendedor"));

        jLabel5.setText("CPF Vendedor");

        try {
            txtCPFVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFVendedor.setEnabled(false);

        lblNomeVendedor.setText(" ");
        lblNomeVendedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnConsultarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarVendedor.setEnabled(false);
        btnConsultarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPFVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnConsultarVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNomeVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCPFVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeVendedor))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do Pedido"));

        jLabel6.setText("Código do Produto");

        txtCodProduto.setEnabled(false);

        btnConsultarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarProduto.setEnabled(false);
        btnConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProdutoActionPerformed(evt);
            }
        });

        lblDescricao.setText(" ");
        lblDescricao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setText("Qtde Vendida");

        txtQtdeVendida.setEnabled(false);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnAdicionar.setText("Adicionar Item");
        btnAdicionar.setEnabled(false);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnRemover.setText("Remover Item");
        btnRemover.setEnabled(false);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        tblItemPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Prec. Unit.", "Qtde. Vend.", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblItemPedido);

        jLabel8.setText("Valor Total do Pedido");

        lblValTotal.setText(" ");
        lblValTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setText("Qtde de Itens Pedidos");

        lblQtdeItensPedidos.setText(" ");
        lblQtdeItensPedidos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdeVendida)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblQtdeItensPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblValTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemover)
                                .addGap(167, 167, 167))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDescricao)
                        .addComponent(jLabel7)
                        .addComponent(txtQtdeVendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConsultarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblValTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblQtdeItensPedidos)))
        );

        btnIncluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        DecimalFormat df = new DecimalFormat("#.##");

        int x;
        posProduto = -1;

        for (x = 0; x < produto.size(); x++) {
            if (produto.get(x).getCodigo().equals(txtCodProduto.getText())) {
                posProduto = x;
            }
        }

        if (Double.parseDouble(txtQtdeVendida.getText()) == 0) {
            JOptionPane.showMessageDialog(null, "Quantidade inválida. Insira um valor maior que zero!", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {

            if (Double.parseDouble(txtQtdeVendida.getText()) > produto.get(posProduto).getQtdeEstoque()) {
                JOptionPane.showMessageDialog(null, "Quantidade em estoque menor do que o solicitado!", "Aviso", JOptionPane.ERROR_MESSAGE);
            } else {

                if (objPedido.getCliente().getLimiteDisp() < (Double.parseDouble(txtQtdeVendida.getText()) * produto.get(posProduto).getPreco())) {
                    JOptionPane.showMessageDialog(null, "Limite indisponível!", "Aviso", JOptionPane.ERROR_MESSAGE);
                } else {
                    
                    objItemPedido = new ItemPedido(modTblPedido.getRowCount() + 1, Double.parseDouble(txtQtdeVendida.getText()), produto.get(posProduto));

                    String linha[] = {txtCodProduto.getText(), lblDescricao.getText(), String.valueOf(objItemPedido.getProduto().getPreco()), txtQtdeVendida.getText()};

                    subtotal = Double.parseDouble(txtQtdeVendida.getText()) * objItemPedido.getProduto().getPreco();
                    
                    modTblPedido.addRow(linha);
                    modTblPedido.setValueAt(df.format(subtotal), modTblPedido.getRowCount() - 1, 4);

                    total += subtotal;
                    
                    objPedido.addItemPedido(objItemPedido);
                    
                    lblValTotal.setText(String.valueOf(total));
                    lblQtdeItensPedidos.setText(String.valueOf(modTblPedido.getRowCount()));
                    
                    txtCodProduto.setText(null);
                    lblDescricao.setText(" ");
                    txtQtdeVendida.setText("");
                    
                    txtCodProduto.requestFocus();
                    
                }

            }
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

        if(tblItemPedido.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "A linha não foi selecionada!", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
            String codigo;
            double qtdeVend;

            codigo = (String) modTblPedido.getValueAt(tblItemPedido.getSelectedRow(), 0);

            qtdeVend = Double.parseDouble((String) modTblPedido.getValueAt(tblItemPedido.getSelectedRow(), 3));

            if(objPedido.getItemPedidos().get(tblItemPedido.getSelectedRow()).getProduto().getCodigo().equals(codigo)){

                objPedido.getItemPedidos().get(tblItemPedido.getSelectedRow()).getProduto().setQtdeEstoque(
                        objPedido.getItemPedidos().get(tblItemPedido.getSelectedRow()).getProduto().getQtdeEstoque() + qtdeVend);

                objPedido.getCliente().setLimiteDisp(objPedido.getCliente().getLimiteDisp()
                    + Double.parseDouble((String) modTblPedido.getValueAt(tblItemPedido.getSelectedRow(), 4)));

            }

            objPedido.getItemPedidos().remove(tblItemPedido.getSelectedRow());

            total -= Double.parseDouble((String) modTblPedido.getValueAt(tblItemPedido.getSelectedRow(), 4));

            modTblPedido.removeRow(tblItemPedido.getSelectedRow());

            lblValTotal.setText(String.valueOf(total));
            lblQtdeItensPedidos.setText(String.valueOf(modTblPedido.getRowCount()));
            
            txtCodProduto.requestFocus();

        }
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed

        pedido.add(objPedido);

        subtotal = 0;
        total = 0;

        lblNomeCliente.setText(" ");
        lblNomeVendedor.setText(" ");
        lblValTotal.setText(" ");
        lblQtdeItensPedidos.setText(" ");
        
        modTblPedido.setRowCount(0);
        
        txtNumPedido.setText(null);
        txtDtPedido.setText(null);
        cbxFormaPagto.setSelectedIndex(0);
        txtCPFCliente.setText(null);
        lblNomeCliente.setText(" ");
        txtCPFVendedor.setText(null);
        lblNomeVendedor.setText(" ");
        txtCodProduto.setText(null);
        lblDescricao.setText(" ");
        txtQtdeVendida.setText(null);
        lblValTotal.setText(" ");
        lblQtdeItensPedidos.setText(" ");
        
        txtNumPedido.setEnabled(true);
        txtDtPedido.setEnabled(false);
        cbxFormaPagto.setEnabled(false);
        txtCPFCliente.setEnabled(false);
        txtCPFVendedor.setEnabled(false);
        txtCodProduto.setEnabled(false);
        txtQtdeVendida.setEnabled(false);

        btnConsultarPedido.setEnabled(true);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnConsultarProduto.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnAdicionar.setEnabled(false);
        btnRemover.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        txtNumPedido.requestFocus();

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        if(cbxFormaPagto.getSelectedIndex() == 0){
            objPedido.setFormaPagto(true);
        }else{
            objPedido.setFormaPagto(false);
        }
        
        subtotal = 0;
        total = 0;
        
        txtNumPedido.setText(null);
        txtDtPedido.setText(null);
        cbxFormaPagto.setSelectedIndex(0);
        txtCPFCliente.setText(null);
        lblNomeCliente.setText(" ");
        txtCPFVendedor.setText(null);
        lblNomeVendedor.setText(" ");
        txtCodProduto.setText(null);
        lblDescricao.setText(" ");
        txtQtdeVendida.setText(null);
        lblValTotal.setText(" ");
        lblQtdeItensPedidos.setText(" ");
        
        modTblPedido.setRowCount(0);
        
        txtNumPedido.setEnabled(true);
        txtDtPedido.setEnabled(false);
        cbxFormaPagto.setEnabled(false);
        txtCPFCliente.setEnabled(false);
        txtCPFVendedor.setEnabled(false);
        txtCodProduto.setEnabled(false);
        txtQtdeVendida.setEnabled(false);

        btnConsultarPedido.setEnabled(true);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnConsultarProduto.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnAdicionar.setEnabled(false);
        btnRemover.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        txtNumPedido.requestFocus();

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        for(int y = 0; y < objPedido.getItemPedidos().size(); y++){
            
            objPedido.getItemPedidos().get(y).getProduto().setQtdeEstoque(
                                objPedido.getItemPedidos().get(y).getProduto().getQtdeEstoque()
                                + objPedido.getItemPedidos().get(y).getQtdeVendida());

            objPedido.getCliente().setLimiteDisp(objPedido.getCliente().getLimiteDisp()
                                + (objPedido.getItemPedidos().get(y).getQtdeVendida()
                                * objPedido.getItemPedidos().get(y).getProduto().getPreco()));
             
        }
        
        if(posPedido > -1){
            pedido.remove(posPedido);
            posPedido = -1;
        }
        
        subtotal = 0;
        total = 0;
        
        txtNumPedido.setText(null);
        txtDtPedido.setText(null);
        cbxFormaPagto.setSelectedIndex(0);
        txtCPFCliente.setText(null);
        lblNomeCliente.setText(" ");
        txtCPFVendedor.setText(null);
        lblNomeVendedor.setText(" ");
        txtCodProduto.setText(null);
        lblDescricao.setText(" ");
        txtQtdeVendida.setText(null);
        lblValTotal.setText(" ");
        lblQtdeItensPedidos.setText(" ");
        
        modTblPedido.setRowCount(0);
        
        txtNumPedido.setEnabled(true);
        txtDtPedido.setEnabled(false);
        cbxFormaPagto.setEnabled(false);
        txtCPFCliente.setEnabled(false);
        txtCPFVendedor.setEnabled(false);
        txtCodProduto.setEnabled(false);
        txtQtdeVendida.setEnabled(false);

        btnConsultarPedido.setEnabled(true);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnConsultarProduto.setEnabled(false);
        btnIncluir.setEnabled(false);
        btnAdicionar.setEnabled(false);
        btnRemover.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        txtNumPedido.requestFocus();

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPedidoActionPerformed

        DecimalFormat df = new DecimalFormat("#.##");

        int x;
        posPedido = -1;

        for (x = 0; x < pedido.size(); x++) {
            if (pedido.get(x).getNumero().equals(txtNumPedido.getText())) {
                posPedido = x;
            }
        }

        if (posPedido > -1) {
            objPedido = pedido.get(posPedido);

            txtDtPedido.setText(objPedido.getDataEmissao());
            
            if(objPedido.getFormaPagto() == true){
                cbxFormaPagto.setSelectedIndex(0);
            }else{
                cbxFormaPagto.setSelectedIndex(1);
            }
            
            txtCPFCliente.setText(objPedido.getCliente().getCpf());
            lblNomeCliente.setText(objPedido.getCliente().getNome());
            txtCPFVendedor.setText(objPedido.getVendedor().getCpf());
            lblNomeVendedor.setText(objPedido.getVendedor().getNome());

            for (int i = 0; i < objPedido.getItemPedidos().size(); i++){
                
                String linha[] = {objPedido.getItemPedidos().get(i).getProduto().getCodigo(),
                    objPedido.getItemPedidos().get(i).getProduto().getDescricao(),
                    String.valueOf(objPedido.getItemPedidos().get(i).getProduto().getPreco()),
                    String.valueOf(objPedido.getItemPedidos().get(i).getQtdeVendida())};

                subtotal = objPedido.getItemPedidos().get(i).getQtdeVendida()
                        * objPedido.getItemPedidos().get(i).getProduto().getPreco();

                modTblPedido.addRow(linha);
                modTblPedido.setValueAt(df.format(subtotal), modTblPedido.getRowCount() - 1, 4);

                total += subtotal;

                lblValTotal.setText(String.valueOf(total));
                lblQtdeItensPedidos.setText(String.valueOf(modTblPedido.getRowCount()));

            }

            txtNumPedido.setEnabled(false);
            txtDtPedido.setEnabled(false);
            cbxFormaPagto.setEnabled(true);
            txtCPFCliente.setEnabled(false);
            txtCPFVendedor.setEnabled(false);
            txtCodProduto.setEnabled(true);
            txtQtdeVendida.setEnabled(true);

            btnConsultarPedido.setEnabled(false);
            btnConsultarCliente.setEnabled(false);
            btnConsultarVendedor.setEnabled(false);
            btnConsultarProduto.setEnabled(true);
            btnAdicionar.setEnabled(true);
            btnRemover.setEnabled(true);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            
            cbxFormaPagto.requestFocus();

        } else {

            txtDtPedido.setEnabled(true);
            cbxFormaPagto.setEnabled(true);
            txtCPFCliente.setEnabled(true);

            btnConsultarPedido.setEnabled(false);
            btnConsultarCliente.setEnabled(true);

            txtDtPedido.requestFocus();
            
        }

    }//GEN-LAST:event_btnConsultarPedidoActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed

        objPedido = new Pedido(txtNumPedido.getText(), txtDtPedido.getText().replaceAll("/", ""));
        
        if(cbxFormaPagto.getSelectedIndex() == 0){
            objPedido.setFormaPagto(true);
        }else{
            objPedido.setFormaPagto(false);
        }

        int x;
        posCliente = -1;

        for (x = 0; x < cliVend.size(); x++) {
            if ((cliVend.get(x) instanceof Cliente) && (cliVend.get(x).getCpf().equals(txtCPFCliente.getText().replaceAll("[\\.\\-]", "")))) {
                posCliente = x;
            }
        }

        if (posCliente > -1) {
            objCli = (Cliente) cliVend.get(posCliente);

            lblNomeCliente.setText(objCli.getNome());

            txtDtPedido.setEnabled(false);
            cbxFormaPagto.setEnabled(false);
            txtCPFCliente.setEnabled(false);
            btnConsultarCliente.setEnabled(false);
            txtCPFVendedor.setEnabled(true);
            btnConsultarVendedor.setEnabled(true);

            objCli.addPedido(objPedido);
            
            txtCPFVendedor.requestFocus();

        } else {
            JOptionPane.showMessageDialog(null, "CPF inserido não existe!", "Aviso", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnConsultarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVendedorActionPerformed

        int x;
        posVendedor = -1;

        for (x = 0; x < cliVend.size(); x++) {
            if ((cliVend.get(x) instanceof Vendedor) && (cliVend.get(x).getCpf().equals(txtCPFVendedor.getText().replaceAll("[\\.\\-]", "")))) {
                posVendedor = x;
            }
        }

        if (posVendedor > -1) {
            objVend = (Vendedor) cliVend.get(posVendedor);

            lblNomeVendedor.setText(objVend.getNome());

            txtCPFVendedor.setEnabled(false);
            btnConsultarVendedor.setEnabled(false);
            txtCodProduto.setEnabled(true);
            btnConsultarProduto.setEnabled(true);
            btnIncluir.setEnabled(true);

            objVend.addPedido(objPedido);
            
            txtCodProduto.requestFocus();

        } else {
            JOptionPane.showMessageDialog(null, "CPF inserido não existe!", "Aviso", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnConsultarVendedorActionPerformed

    private void btnConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProdutoActionPerformed

        int x;
        posProduto = -1;

        for (x = 0; x < produto.size(); x++) {
            if (produto.get(x).getCodigo().equals(txtCodProduto.getText())) {
                posProduto = x;
            }
        }

        if (posProduto > -1) {
            objProd = produto.get(posProduto);

            lblDescricao.setText(objProd.getDescricao());

            txtQtdeVendida.setEnabled(true);
            btnAdicionar.setEnabled(true);
            btnRemover.setEnabled(true);
            
            txtQtdeVendida.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Código de produto inválido!", "Aviso", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnConsultarProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarPedido;
    private javax.swing.JButton btnConsultarProduto;
    private javax.swing.JButton btnConsultarVendedor;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxFormaPagto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeVendedor;
    private javax.swing.JLabel lblQtdeItensPedidos;
    private javax.swing.JLabel lblValTotal;
    private javax.swing.JTable tblItemPedido;
    private javax.swing.JFormattedTextField txtCPFCliente;
    private javax.swing.JFormattedTextField txtCPFVendedor;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JFormattedTextField txtDtPedido;
    private javax.swing.JTextField txtNumPedido;
    private javax.swing.JTextField txtQtdeVendida;
    // End of variables declaration//GEN-END:variables
    private Pedido objPedido;
    private Produto objProd;
    private Cliente objCli;
    private Vendedor objVend;
    private ItemPedido objItemPedido;
    private ArrayList<Pedido> pedido;
    private ArrayList<Pessoa> cliVend;
    private ArrayList<Produto> produto;
    private int posPedido;
    private int posCliente;
    private int posVendedor;
    private int posProduto;
    private double total = 0;
    private double subtotal = 0;
    private DefaultTableModel modTblPedido;
}
